### ISSUE TITLE
SyntaxError: invalid character in identifier

### ISSUE THREAD

**Issue by Rule83** [Chick3nman/ether2hashcat.py#1]
I can't get by the SyntaxError as noted below (I'm working on Mac).
- After the error, first of all I've copied and paste the code
 to text pad to hopefully clean it from any html etc. No change in result.
- Then I've searched the internet and came by a possible solution to add # encoding=utf8 to the script. No change in result.
- After a few new hours of searching, I came across a solution to update my Python version (I than did) and (besides using "python3 ether2hashcat.py" to execute) I've also added #!/usr/bin/env python3. No change in result.
- At last I've copied and pasted the contents of my son file to a new file called mistTest.txt in stead of using my son file called the same, but within '.txt'. No change in result.

Here's the error I'm stil getting after all my efforts:
File "ether2hashcat.py", line 6
    with open(‘mistTest.txt’) as wallet_file:
                      ^
SyntaxError: invalid character in identifier

**Comment by Chick3nman** [comment]
This script is written for Python 2.7 however it's been superseded by @kholia's script here: https://github.com/magnumripper/JohnTheRipper/pull/2525
Please use his going forward.
